global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prkdb'
    static_configs:
      - targets: ['localhost:9091']
        labels:
          instance: 'prkdb-node1'
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
